approved = [
  "mit",
  "apache-2.0",
  "bsd-3-clause",
  "bsd-2-clause",
  "mpl-2.0",
]

ignored = [
  "cloud.google.com/go",
  "emperror.dev/errors",
  "github.com/Shopify/sarama",
  "github.com/banzaicloud/bank-vaults/pkg/sdk",
  "github.com/banzaicloud/istio-client-go",
  "github.com/banzaicloud/istio-operator",
  "github.com/banzaicloud/k8s-objectmatcher",
  "github.com/banzaicloud/kafka-operator/api",
  "github.com/beorn7/perks",
  "github.com/census-instrumentation/opencensus-proto",
  "github.com/cespare/xxhash/v2",
  "github.com/cncf/udpa/go",
  "github.com/davecgh/go-spew",
  "github.com/eapache/go-resiliency",
  "github.com/eapache/go-xerial-snappy",
  "github.com/eapache/queue",
  "github.com/envoyproxy/go-control-plane",
  "github.com/envoyproxy/protoc-gen-validate",
  "github.com/evanphx/json-patch",
  "github.com/fatih/color",
  "github.com/fsnotify/fsnotify",
  "github.com/ghodss/yaml",
  "github.com/go-logr/logr",
  "github.com/go-logr/zapr",
  "github.com/gogo/protobuf",
  "github.com/golang/groupcache",
  "github.com/golang/protobuf",
  "github.com/golang/snappy",
  "github.com/google/go-cmp",
  "github.com/google/gofuzz",
  "github.com/google/uuid",
  "github.com/googleapis/gnostic",
  "github.com/goph/emperror",
  "github.com/hashicorp/errwrap",
  "github.com/hashicorp/go-cleanhttp",
  "github.com/hashicorp/go-hclog",
  "github.com/hashicorp/go-multierror",
  "github.com/hashicorp/go-retryablehttp",
  "github.com/hashicorp/go-rootcerts",
  "github.com/hashicorp/go-sockaddr",
  "github.com/hashicorp/go-uuid",
  "github.com/hashicorp/golang-lru",
  "github.com/hashicorp/hcl",
  "github.com/hashicorp/vault/api",
  "github.com/hashicorp/vault/sdk",
  "github.com/imdario/mergo",
  "github.com/jcmturner/gofork",
  "github.com/jetstack/cert-manager",
  "github.com/json-iterator/go",
  "github.com/klauspost/compress",
  "github.com/lestrrat-go/backoff",
  "github.com/magiconair/properties",
  "github.com/mattn/go-colorable",
  "github.com/mattn/go-isatty",
  "github.com/matttproud/golang_protobuf_extensions",
  "github.com/mitchellh/go-homedir",
  "github.com/mitchellh/mapstructure",
  "github.com/modern-go/concurrent",
  "github.com/modern-go/reflect2",
  "github.com/pavel-v-chernykh/keystore-go",
  "github.com/pelletier/go-toml",
  "github.com/pierrec/lz4",
  "github.com/pkg/errors",
  "github.com/prometheus/client_golang",
  "github.com/prometheus/client_model",
  "github.com/prometheus/common",
  "github.com/prometheus/procfs",
  "github.com/rcrowley/go-metrics",
  "github.com/ryanuber/go-glob",
  "github.com/sirupsen/logrus",
  "github.com/spf13/afero",
  "github.com/spf13/cast",
  "github.com/spf13/jwalterweatherman",
  "github.com/spf13/pflag",
  "github.com/spf13/viper",
  "go.uber.org/atomic",
  "go.uber.org/multierr",
  "go.uber.org/zap",
  "golang.org/x/crypto",
  "golang.org/x/net",
  "golang.org/x/oauth2",
  "golang.org/x/sys",
  "golang.org/x/text",
  "golang.org/x/time",
  "gomodules.xyz/jsonpatch/v2",
  "google.golang.org/genproto",
  "google.golang.org/grpc",
  "gopkg.in/fsnotify.v1",
  "gopkg.in/inf.v0",
  "gopkg.in/jcmturner/aescts.v1",
  "gopkg.in/jcmturner/dnsutils.v1",
  "gopkg.in/jcmturner/gokrb5.v7",
  "gopkg.in/jcmturner/rpc.v1",
  "gopkg.in/square/go-jose.v2",
  "gopkg.in/yaml.v2",
  "k8s.io/api",
  "k8s.io/apiextensions-apiserver",
  "k8s.io/apimachinery",
  "k8s.io/client-go",
  "k8s.io/klog",
  "k8s.io/kube-openapi",
  "k8s.io/utils",
  "sigs.k8s.io/controller-runtime",
  "sigs.k8s.io/structured-merge-diff/v3",
  "sigs.k8s.io/yaml",
]
