apiVersion: banzaicloud.banzaicloud.io/v1alpha1
kind: KafkaCluster
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: kafka
spec:
  # Add fields here
  brokers: 3
  annotations: {}
  image: "wurstmeister/kafka:2.12-2.1.0"
  brokerConfig: |
    num.network.threads=2
    log.dirs=/kafka-logs/kafka
    zookeeper.connect=example-zookeepercluster-client.zookeeper:2181
    default.replication.factor=3
  listeners:
    externalListener:
      - type: "plaintext"
        name: "externalka"
        externalStartingPort: 19090
        containerPort: 9094
    internalListener:
      - type: "plaintext"
        name: "internalka"
        containerPort: 29092
        usedForInnerBrokerCommunication: true
  serviceAccount: ""
  storageSize: "1Gi"
