apiVersion: banzaicloud.banzaicloud.io/v1alpha1
kind: KafkaCluster
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: kafkacluster-test
spec:
  # Add fields here
  brokers: 2
  annotations: {}
  image: "wurstmeister/kafka:2.12-2.1.0"
  brokerConfig: >-
    num.network.threads=2
    log.dirs=/kafka-logs
  serviceAccount: ""
  storageSize: "1Gi"
