apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: prometheus
rules:
- apiGroups: [""]
  resources:
  - nodes
  - services
  - endpoints
  - pods
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources:
  - configmaps
  verbs: ["get"]
- nonResourceURLs: ["/metrics"]
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: prometheus
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: prometheus
subjects:
- kind: ServiceAccount
  name: prometheus
  namespace: default
---
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: kafka-prometheus
spec:
  serviceAccountName: prometheus
  alerting:
    alertmanagers:
    - namespace: kafka
      name: kafka-operator-operator-alertmanager-manager
      port: alerts
  serviceMonitorSelector:
    matchLabels:
      app: kafka
      kafka_cr: kafka
  ruleSelector:
    matchLabels:
      prometheus: kafka-rules
  resources:
    requests:
      memory: 400Mi
  enableAdminAPI: false
