serverFiles:
  alerts:
    groups:
    - name: TestAlert
      rules:
      - alert: PodAllert
        expr: kubelet_running_pod_count > 15
        for: 1m
        labels:
          severity: alert
        annotations:
          description: 'more than 15 pods (current value is: {{ $value }})'
          summary: 'too many pods'
          command: 'decommission'
