name: Docker
on:
  push:
    branches:
      - master
    tags:
      - "^v?[0-9]+.[0-9]+.[0-9]+"
jobs:
  docker:
    name: Docker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build kafka-operator
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.CR_PAT }}
          registry: ghcr.io
          repository: banzaicloud/kafka-operator
          dockerfile: Dockerfile
          tag_with_ref: true
          add_git_labels: true
